### ISSUE TITLE
关于BTM的问题

### ISSUE THREAD

**Issue by yyyyeed123** [liguoyu1/python#4]
您好，因为学习原因需要构建BTM模型，于是我就照着您的搭了一个简易版的，然后输出结果只有话题概率的列表，没有相应主题。我想请问您的模型中是哪部分实现返回筛选出来的主题？麻烦了

**Comment by liguoyu1** [comment]
您好，感谢您的提问，在python/TopicModel/BTM/BTMModel.py中def sentence_topic(self, sentence, topic_num=1, min_pro=0.01)函数是获取query 的主题标签的函数，输入是句子的文本，需要获取的topic 数量 top K ,以及获取的topic 的阈值过滤(只有大于阈值的，并且是top K 的topic 方能出现在返回值中)

**Comment by liguoyu1** [comment]
由于业务需要，本人仅实现了该算法，并没有优化其算法流程，如果可以的话可以多多交流，以期实现该算法的流程优化！谢谢！
